# CPLEX Solver Parameters
Feasib_Tol: 1.0e-06 # Constraint (primal) feasibility tolerances.
Optimal_Tol: 1e-4 # Dual feasibility tolerances.
Pre_Solve: 1 # Controls presolve level.
#AggFill: # Allowed fill during presolve aggregation.
#PreDual: # Presolve dualization.
TimeLimit: 110000 # Limits total time solver.
MIPGap: 1e-4 # Relative (p.u. of optimal) mixed integer optimality tolerance for MIP problems (ignored otherwise).
Method: 2 #-1 # Algorithm used to solve continuous models (including MIP root relaxation).
BarConvTol: 1.0e-08 # Barrier convergence tolerance (determines when barrier terminates).
NumericFocus: 0 # Numerical precision emphasis.
#BarObjRng: # Sets the maximum absolute value of the objective function.
SolutionType: 2 # Solution type for LP or QP.
