NetworkExpansion: 1
ModelingToGenerateAlternativeIterations: 3
ParameterScale: 1
EnergyShareRequirement: 0
PrintModel: 0
TimeDomainReduction: 1
Trans_Loss_Segments: 1
CapacityReserveMargin: 0
ModelingtoGenerateAlternativeSlack: 0.1
MethodofMorris: 0
StorageLosses: 1
MultiStage: 0
OverwriteResults: 0
UCommit: 2
ModelingToGenerateAlternatives: 0
MaxCapReq: 0
MinCapReq: 1
CO2Cap: 2
WriteShadowPrices: 1
