# CBC Solver Parameters
# Common solver settings
TimeLimit: 110000       # Solution timeout limit. For example, set_optimizer_attribute(model, "seconds", 60.0).

#CBC-specific solver settings
logLevel: 1             # Set to 1 to enable solution output. For example, set_optimizer_attribute(model, "logLevel", 1).
maxSolutions: -1        # Terminate after this many feasible solutions have been found. For example, set_optimizer_attribute(model, "maxSolutions", 1).
maxNodes: 2000         # Terminate after this many branch-and-bound nodes have been evaluated. For example, set_optimizer_attribute(model, "maxNodes", 1).
allowableGap:  1     # Terminate after optimality gap is less than this value (on an absolute scale). For example, set_optimizer_attribute(model, "allowableGap", 0.05).
ratioGap: 0.01          # Terminate after optimality gap is smaller than this relative fraction. For example, set_optimizer_attribute(model, "allowableGap", 0.05).
threads: 2              # Set the number of threads to use for parallel branch & bound. For example, set_optimizer_attribute(model, "threads", 2)
